removed warnings on npm start, unused vars, etc
seba-pitra/e-commerce-NFT pull request #62
Opened 2022-12-13 23:34 UTC by molinaro-77

elimine todas las warnings. volvi a poner algunas lineas. la explicacion en la pestaña files changed.

2022-12-13 23:47 UTC, molinaro-77 commented on client/package-lock.json
>          "@testing-library/react": "^11.2.6",
dependencias de material ui para flechas en filtros de ordenamiento... y para usar mas adelante en otras cosas

2022-12-13 23:47 UTC, molinaro-77 commented on client/package.json
>    "dependencies": {
dependencias de material ui

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/App.js
> +import { Route, Switch } from 'react-router-dom';
vuelvo a agregar switch

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/App.js
>        <React.Fragment>
el nav es necesario que este en todos los path... y luego se oculta mediante otras instrucciones... en un futuro commit hago esa parte.

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/App.js
> -      <Route path='/home' render={()=><NFTNav/>} />
como esta aca... por alguna razon ... no estaba tomando el componente home... renderizaba el nav sin el homepage.

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/App.js
> +        <Switch>
el switch es importante para que no me renderice el not found exception en todos los path.. sino que lo renderice siempre y cuando no este en ninguno de los path validos declarados

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/404Page/404Page.jsx
> +        HELLO!!!
esto estaba aca para comprobar el argumento anterior... pero mas alla de eso estaria bueno diseñar una 404

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/CreateNft/CreateNft.jsx
unused vars

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/CreateNft/PreviewNft/PreviewNft.jsx
>              />
genera un warning

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/FilterOptrions/Filtering/Filtering.jsx
>    const [selectedCategory, setSelectedCategory] = useState("");
unused var

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/FilterOptrions/Filtering/Filtering.jsx
>  import "./Filtering.css";
unused var

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/FilterOptrions/Filtering/Filtering.jsx
>      count = 0;
para recorrer un array, solo recorrerlo es mejor usar for each... lo demas genera warnings

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/FilterOptrions/NFTSPerPageSelector/NFTSPerPageSelector.jsx
> +// }
comente todo este componente para diseñarlo despues

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/FilterOptrions/Options.jsx
>  import { useDispatch } from "react-redux";
unused var

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/FilterOptrions/Ordering/Ordering.css
> -} */
borre lo que estaba comentado

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/FilterOptrions/Ordering/Ordering.jsx
commented unused vars

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/FilterOptrions/Ordering/Ordering.jsx
>          </button>
aca estan los iconos de flecha arriba o flecha abajo que cambian dependiendo del estado

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/FilterOptrions/Ordering/Ordering.jsx
>            onClick={() => orderByPrice()}
esto originalmente lo cambie para que no empiecen estando de color los botones... pero creo que lo ideal seria sacarle los colores completamente... las flechas ya indican

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/FilterOptrions/PriceSelector/PriceSelector.jsx
unused var

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/HomePage/HomePage.jsx
> +import { useEffect } from 'react';
unused vars

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/Footer/Footer.jsx
> -import {Link} from 'react-router-dom';
unused var

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/LandingPage/LandingPage.jsx
>              <h1 className={styles["landing-subtitle"]}>
corregido nombre de la empresa.

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/NFTCard/NFTCard.jsx
>              />
genera un warning

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/NFTNav/NFTNav.jsx
>  import SearchBar from '../SearchBar/SearchBar'
unused var

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/NFTNav/NFTNav.jsx
unused var

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/components/NFTNav/NFTNav.jsx
> -	{/* Pim Pum Pam*/}
genera warning

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/redux/reducer/index.js
>        });
map espera un return... genera warning

2022-12-13 23:47 UTC, molinaro-77 commented on client/src/utils/index.js
>      }
me falto el default... generaba un warning

2022-12-13 23:49 UTC, valcoellar approved these changes

2022-12-14 02:05 UTC, FranSchlatter requested changes
Lo mismo q el otro, me estas pisando los cambios de hoy xd

2022-12-14 14:57 UTC, FranSchlatter approved these changes

2022-12-14 14:57 UTC, merged